source "https://rubygems.org"

gem "rails", "~> 8.0.2"
gem "propshaft"
gem "bootstrap", "~> 5.3"
gem "cssbundling-rails"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"
gem "devise"
# Use the Puma web server
gem "puma", ">= 5.0"
# Use JavaScript with ESM import maps
gem "importmap-rails"
# Hotwire (Turbo + Stimulus)
gem "turbo-rails"
gem "stimulus-rails"
# Build JSON APIs
gem "jbuilder"

# Use Active Model has_secure_password
gem "bcrypt", "~> 3.1.7"

# Windows timezone compatibility
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Solid stack components
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# Faster boot times
gem "bootsnap", require: false

# Deploy with Kamal
gem "kamal", require: false

# Performance on Puma
gem "thruster", require: false

# Image variants (Active Storage)
gem "image_processing", "~> 1.2"

# Cloudinary storage
gem "cloudinary"
gem "activestorage-cloudinary-service"

# HTTP persistent connections
gem "net-http-persistent"

# OCR and Vision
gem "rtesseract"
gem "google-cloud-vision"
gem "mini_magick"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "dotenv-rails"
  gem "sqlite3"  # Optional: if you use SQLite in dev/test
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end

# Tailwind support
gem "tailwindcss-rails", "~> 4.3"
